/**
 *  Category actions enum
 */
export enum CategoryActionsEnum {
  GET_CATEGORY_LIST_REQUESTED = "CATEGORY/GET_CATEGORY_LIST_REQUESTED",
  GET_CATEGORY_LIST_SUCCESS = "CATEGORY/GET_CATEGORY_LIST_SUCCESS",
  GET_CATEGORY_LIST_FAILURE = "CATEGORY/GET_CATEGORY_LIST_FAILURE",
  CATEGORY_SET_SELECTED_ITEM = "CATEGORY/CATEGORY_SET_SELECTED_ITEM",
  GET_CATEGORY_REQUESTED = "CATEGORY/GET_CATEGORY_REQUESTED",
  GET_CATEGORY_FETCHED = "CATEGORY/GET_CATEGORY_FETCHED",
  GET_CATEGORY_FAILURE = "CATEGORY/GET_CATEGORY_FAILURE",
  ADD_CATEGORY_REQUESTED = "CATEGORY/ADD_CATEGORY_REQUESTED",
  ADD_CATEGORY_FAILURE = "CATEGORY/ADD_CATEGORY_FAILURE",
  ADD_CATEGORY_SUCCESS = "CATEGORY/ADD_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_REQUESTED = "CATEGORY/UPDATE_CATEGORY_REQUESTED",
  UPDATE_CATEGORY_FAILURE = "CATEGORY/UPDATE_CATEGORY_FAILURE",
  UPDATE_CATEGORY_SUCCESS = "CATEGORY/UPDATE_CATEGORY_SUCCESS",
  UPDATE_ORDER_REQUESTED = "CATEGORY/UPDATE_ORDER_REQUESTED",
  UPDATE_ORDER_SUCCESS = "CATEGORY/UPDATE_ORDER_SUCCESS",
  UPDATE_ORDER_FAILURE = "CATEGORY/UPDATE_ORDER_FAILURE",
  CATEGORY_CLEAR_ERROR = "CATEGORY/CATEGORY_CLEAR_ERROR",
  CATEGORY_CLEAR_STATE = "CATEGORY/CATEGORY_CLEAR_STATE",
  CATEGORY_SET_ORDER = "CATEGORY/CATEGORY_SET_ORDER",
  CATEGORY_TOGGLE_ITEM = "CATEGORY/CATEGORY_TOGGLE_ITEM"
}