/**
 *  SERVICE actions enum
 */
export enum ServicesActionsEnum {
  GET_SERVICE_LIST_REQUESTED = "SERVICE/GET_SERVICE_LIST_REQUESTED",
  GET_SERVICE_LIST_SUCCESS = "SERVICE/GET_SERVICE_LIST_SUCCESS",
  GET_SERVICE_LIST_FAILURE = "SERVICE/GET_SERVICE_LIST_FAILURE",
  SERVICE_SET_SELECTED_ITEM = "SERVICE/SERVICE_SET_SELECTED_ITEM",
  GET_SERVICE_REQUESTED = "SERVICE/GET_SERVICE_REQUESTED",
  GET_SERVICE_FETCHED = "SERVICE/GET_SERVICE_FETCHED",
  GET_SERVICE_FAILURE = "SERVICE/GET_SERVICE_FAILURE",
  ADD_SERVICE_REQUESTED = "SERVICE/ADD_SERVICE_REQUESTED",
  ADD_SERVICE_FAILURE = "SERVICE/ADD_SERVICE_FAILURE",
  ADD_SERVICE_SUCCESS = "SERVICE/ADD_SERVICE_SUCCESS",

  UPDATE_SERVICE_REQUESTED = "SERVICE/UPDATE_SERVICE_REQUESTED",
  UPDATE_SERVICE_FAILURE = "SERVICE/UPDATE_SERVICE_FAILURE",
  UPDATE_SERVICE_SUCCESS = "SERVICE/UPDATE_SERVICE_SUCCESS",

  UPDATE_ORDER_REQUESTED = "SERVICE/UPDATE_ORDER_REQUESTED",
  UPDATE_ORDER_SUCCESS = "SERVICE/UPDATE_ORDER_SUCCESS",
  UPDATE_ORDER_FAILURE = "SERVICE/UPDATE_ORDER_FAILURE",

  DELETE_SERVICE_REQUESTED = "SERVICE/DELETE_SERVICE_REQUESTED",
  DELETE_SERVICE_SUCCESS = "SERVICE/DELETE_SERVICE_SUCCESS",
  DELETE_SERVICE_FAILURE = "SERVICE/DELETE_SERVICE_FAILURE",

  SERVICE_CLEAR_ERROR = "SERVICE/SERVICE_CLEAR_ERROR",
  SERVICE_CLEAR_STATE = "SERVICE/SERVICE_CLEAR_STATE",
  SERVICE_SET_ORDER = "SERVICE/SERVICE_SET_ORDER",
  UPDATE_AVATAR_REQUESTED = "SERVICE/UPDATE_AVATAR_REQUESTED",
  UPDATE_AVATAR_SUCCESS = "SERVICE/UPDATE_AVATAR_SUCCESS",
  UPDATE_AVATAR_FAILURE = "SERVICE/UPDATE_AVATAR_FAILURE",
  SERVICE_TOGGLE_SERVICE = "SERVICE/SERVICE_TOGGLE_ITEM",
}