/**
 *  Booking settings actions enum
 */
export enum BookingSettingsActionsEnum {
  GET_BOOKING_SETTINGS_REQUESTED = "BOOKING_SETTINGS/GET_BOOKING_SETTINGS_REQUESTED",
  GET_BOOKING_SETTINGS_FAILURE = "BOOKING_SETTINGS/GET_BOOKING_SETTINGS_FAILURE",
  GET_BOOKING_SETTINGS_SUCCESS = "BOOKING_SETTINGS/GET_BOOKING_SETTINGS_SUCCESS",
  UPDATE_BOOKING_SETTINGS_REQUESTED = "BOOKING_SETTINGS/UPDATE_BOOKING_SETTINGS_REQUESTED",
  UPDATE_BOOKING_SETTINGS_FAILURE = "BOOKING_SETTINGS/UPDATE_BOOKING_SETTINGS_FAILURE",
  UPDATE_BOOKING_SETTINGS_SUCCESS = "BOOKING_SETTINGS/UPDATE_BOOKING_SETTINGS_SUCCESS",
  BOOKING_SETTINGS_CLEAR_ERROR = "BOOKING_SETTINGS/LOCATION_CLEAR_ERROR",
  BOOKING_SETTINGS_CLEAR_STATE = "BOOKING_SETTINGS/LOCATION_CLEAR_STATE",
}