/**
 *  Locations actions enum
 */
export enum LocationActionsEnum {
  GET_LOCATION_LIST_REQUESTED = "LOCATION/GET_LOCATION_LIST_REQUESTED",
  GET_LOCATION_LIST_SUCCESS = "LOCATION/GET_LOCATION_LIST_SUCCESS",
  GET_LOCATION_LIST_FAILURE = "LOCATION/GET_LOCATION_LIST_FAILURE",
  ADD_LOCATION_REQUESTED = "LOCATION/ADD_LOCATION_REQUESTED",
  ADD_LOCATION_FAILURE = "LOCATION/ADD_LOCATION_FAILURE",
  ADD_LOCATION_SUCCESS = "LOCATION/ADD_LOCATION_SUCCESS",
  LOCATION_CLEAR_ERROR = "LOCATION/LOCATION_CLEAR_ERROR",
  LOCATION_CLEAR_STATE = "LOCATION/LOCATION_CLEAR_STATE",
}