/**
 *  Employee actions enum
 */
export enum EmployeeActionsEnum {
  GET_EMPLOYEE_LIST_REQUESTED = "EMPLOYEE/GET_EMPLOYEE_LIST_REQUESTED",
  GET_EMPLOYEE_LIST_SUCCESS = "EMPLOYEE/GET_EMPLOYEE_LIST_SUCCESS",
  GET_EMPLOYEE_LIST_FAILURE = "EMPLOYEE/GET_EMPLOYEE_LIST_FAILURE",
  EMPLOYEE_SET_SELECTED_ITEM = "EMPLOYEE/EMPLOYEE_SET_SELECTED_ITEM",
  GET_EMPLOYEE_REQUESTED = "EMPLOYEE/GET_EMPLOYEE_REQUESTED",
  GET_EMPLOYEE_FETCHED = "EMPLOYEE/GET_EMPLOYEE_FETCHED",
  GET_EMPLOYEE_FAILURE = "EMPLOYEE/GET_EMPLOYEE_FAILURE",
  ADD_EMPLOYEE_REQUESTED = "EMPLOYEE/ADD_EMPLOYEE_REQUESTED",
  ADD_EMPLOYEE_FAILURE = "EMPLOYEE/ADD_EMPLOYEE_FAILURE",
  ADD_EMPLOYEE_SUCCESS = "EMPLOYEE/ADD_EMPLOYEE_SUCCESS",
  UPDATE_EMPLOYEE_REQUESTED = "EMPLOYEE/UPDATE_EMPLOYEE_REQUESTED",
  UPDATE_EMPLOYEE_FAILURE = "EMPLOYEE/UPDATE_EMPLOYEE_FAILURE",
  UPDATE_EMPLOYEE_SUCCESS = "EMPLOYEE/UPDATE_EMPLOYEE_SUCCESS",
  UPDATE_AVATAR_REQUESTED = "EMPLOYEE/UPDATE_AVATAR_REQUESTED",
  UPDATE_AVATAR_FAILURE = "EMPLOYEE/UPDATE_AVATAR_FAILURE",
  UPDATE_AVATAR_SUCCESS = "EMPLOYEE/UPDATE_AVATAR_SUCCESS",
  UPDATE_ORDER_REQUESTED = "EMPLOYEE/UPDATE_ORDER_REQUESTED",
  UPDATE_ORDER_SUCCESS = "EMPLOYEE/UPDATE_ORDER_SUCCESS",
  UPDATE_ORDER_FAILURE = "EMPLOYEE/UPDATE_ORDER_FAILURE",
  EMPLOYEE_CLEAR_ERROR = "EMPLOYEE/EMPLOYEE_CLEAR_ERROR",
  EMPLOYEE_CLEAR_STATE = "EMPLOYEE/EMPLOYEE_CLEAR_STATE",
  EMPLOYEE_SET_ORDER = "EMPLOYEE/EMPLOYEE_SET_ORDER",
  EMPLOYEE_TOGGLE_SERVICE = "EMPLOYEE/EMPLOYEE_TOGGLE_ITEM"
}